name: trunk

on:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: [14.x, 16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install Dependencies
        run: yarn install --immutable
      - run: yarn build
      - run: yarn test

  release-canary:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: prisma-labs/dripip@master
        with:
          npmToken: ${{secrets.NPM_TOKEN}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
